POST http://localhost:8081/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI0Nzg2NDkyLCJ1c2VySUQiOjJ9.Rq8gssYDJXyrirmHlw9Hi3TwR5k4Ew7gzYRClg5SEVs

{
    "name": "Test event ",
    "description": "Test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}